import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    borderRadius: {
      none: "0",
      0.5: "2px",
      1: "4px",
      1.5: "6px",
      2: "8px",
      2.5: "10px",
      3: "12px",
      3.5: "14px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      12: "48px",
      13: "52px",
      14: "56px",
      15: "60px",
      16: "64px",
      full: "9999px",
    },
    fontFamily: {
      display: ["var(--font-helvetica)"],
    },
    lineHeight: {
      1: "4px",
      2: "8px",
      3: "12px",
      4: "16px",
      5: "20px",
      6: "24px",
      7: "28px",
      8: "32px",
      9: "36px",
      10: "40px",
      11: "44px",
      12: "48px",
      13: "52px",
      14: "56px",
      15: "60px",
      16: "64px",
      17: "68px",
      18: "72px",
      19: "76px",
      20: "80px",
    },
    screens: {
      "3xs": "300px",
      "2xs": "360px",
      xs: "480px",
      sm: "640px",
      md: "772px",
      lg: "880px",
      xl: "1024px",
      "2xl": "1280px",
      "3xl": "1400px",
      "4xl": "1600px",
      "5xl": "1800px",
      "6xl": "1900px",
      "cover-video": {
        raw: "((min-width: 1900px) or (min-height: 1050px))",
      },
      "md-xl": {
        raw: "(min-width: 772px) and (max-width: 1024px)",
      },
      "sm-height": {
        raw: "(max-height: 500px)",
      },
    },
    extend: {
      animation: {
        gradient: "gradient 2s linear infinite",
        "scale-in": "scale-in 0.2s ease",
        "scale-out": "scale-out 0.2s ease",
        "fade-in": "fade-in 200ms ease",
        "slight-fade-in": "slight-fade-in 200ms ease",
        "slight-fade-out": "slight-fade-out 200ms ease",
        "fade-out": "fade-out 200ms ease",
        glow: "glow 2000ms infinite ease-in-out",
        moveTopToBottom: "moveTopToBottom 125s infinite",
      },
      keyframes: {
        gradient: {
          to: { "background-position": "200% center" },
        },
        "scale-in": {
          from: {
            opacity: "0",
            transform: "rotateX(-10deg) scale(0.9)",
          },
          to: { opacity: "1", transform: "rotateX(0deg) scale(1)" },
        },
        "scale-out": {
          from: { opacity: "1", transform: "rotateX(0deg) scale(1)" },
          to: {
            opacity: "0",
            transform: "rotateX(-10deg) scale(0.95)",
          },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slight-fade-in": {
          from: { opacity: "0.8" },
          to: { opacity: "1" },
        },
        "slight-fade-out": {
          from: { opacity: "0.8" },
          to: { opacity: "1" },
        },
        glow: {
          "0%": {
            textShadow: "0 0 15px rgba(255, 255, 255, 1)",
            color: "rgba(255, 255, 255, 1)",
          },
          "50%": {
            textShadow: "0 0 5px rgba(255, 255, 255, 0.6)",
            color: "rgba(255, 255, 255, 0.8)",
          },
          "100%": {
            textShadow: "0 0 15px rgba(255, 255, 255, 1)",
            color: "rgba(255, 255, 255, 1)",
          },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        moveTopToBottom: {
          "0%": { objectPosition: "top" },
          "50%": { objectPosition: "bottom" },
          "100%": { objectPosition: "top" },
        },
      },
      spacing: {
        5.5: "22px",
        18: "72px",
        21: "84px",
        25: "100px",
        30: "120px",
        34: "136px",
        36: "144px",
        49: "196px",
        50: "200px",
      },
    },
  },
  plugins: ["prettier-plugin-tailwind", require("tailwindcss-animate")],
};
export default config;
